#!/bin/bash

option=$1

if [ -z "$option" ]
then
  openbazaar help
else

  if [[ "$option" == "help" ]] 
  then
    echo "Usage: openbazaar COMMAND"
    echo " "
    echo "   run       #  run local node"
    echo "   stop      #  stop local node"
    echo "   destroy   #  delete local node"
    echo " "
  fi

  if [[ "$option" == "run" ]] 
  then
    echo "Starting OpenBazaar"
    cd ~/OpenBazaar
    ./run.sh "$@"
  fi

  if [[ "$option" == "stop" ]] 
  then
    echo "Stoping OpenBazaar"
    cd ~/OpenBazaar
    ./stop.sh
  fi

  if [[ "$option" == "destroy" ]] 
  then
    
    read -p "You are about to delete OpenBazaar from your computer, everything will de lost. Are you Sure you want to do this? (y/n) " RESP
    if [ "$RESP" = "y" ]; then
      echo "Deleting OpenBazaar"

      openbazaar stop

      sudo rm -rf ~/OpenBazaar

      sudo rm -rf /usr/local/bin/openbazaar

      echo "Done"
    else
      echo ":)"
    fi

  fi

fi
